@startuml Proto_Realizar_Actividad
salt
{+
  {
    ← Salir  |  <b>Animales del campo</b>  |  Ejercicio 2 de 6
  }
  ====
  {
    Progreso: [====    ] 33 %
  }
  ====
  <i>¿Qué animal es este?</i>
  .
  {
    [ 🐄 ]
  }
  .
  ====
  Elige la respuesta:
  {
    [   vaca   ] | [  toro  ]
    [  caballo ] | [  cerdo ]
  }
  ----
  {
    [⏸ Pausar]
  }
}
@enduml
