@startuml

left to right direction
skinparam linetype polyline

state "SESION_CERRADA"          as NoAuth
state "HOME"                    as Home

state "ACTIVIDADES_ABIERTAS"    as ListActividades
state "ACTIVIDAD_ABIERTA"       as DetalleActividad
state "ACTIVIDAD_EN_CURSO"      as ActividadEnCurso
state "RESULTADO_ACTIVIDAD"     as Resultado

state "PROGRESO_ABIERTO"        as Progreso
state "REGISTROS_ABIERTOS"      as ListRegistros

[*] --> NoAuth

NoAuth --> Home : iniciarSesion()

Home --> NoAuth            : cerrarSesion()
Home --> ListActividades   : verActividadesRecomendadas()
Home --> Progreso          : verProgreso()
Home --> ListRegistros     : verRegistros()

' ── ACTIVIDADES ──────────────────────────────────────────────
ListActividades --> DetalleActividad  : abrirActividad()
ListActividades --> Home              : completarNavegacion()

DetalleActividad --> ActividadEnCurso : realizarActividad()
DetalleActividad --> ListActividades  : abrirActividades()

ActividadEnCurso --> ActividadEnCurso : responderEjercicio()
ActividadEnCurso --> ActividadEnCurso : pausarRetomarActividad()
ActividadEnCurso --> Resultado        : completarActividad()

Resultado --> Home                    : finalizarSesion()

' ── PROGRESO ─────────────────────────────────────────────────
Progreso --> Home                     : completarConsulta()

' ── REGISTROS CLÍNICOS ───────────────────────────────────────
ListRegistros --> Home                : completarConsulta()

@enduml
